services:
    ###> doctrine/doctrine-bundle ###
    database:
        image: postgres:${POSTGRES_VERSION:-16}-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-app}
            # You should definitely change the password in production
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
            POSTGRES_USER: ${POSTGRES_USER:-app}
        healthcheck:
            test:
                [
                    'CMD',
                    'pg_isready',
                    '-d',
                    '${POSTGRES_DB:-app}',
                    '-U',
                    '${POSTGRES_USER:-app}',
                ]
            timeout: 5s
            retries: 5
            start_period: 60s
        volumes:
            - database_data:/var/lib/postgresql/data:rw
            # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
            # - ./docker/db/data:/var/lib/postgresql/data:rw

    test_database:
        image: postgres:${POSTGRES_VERSION:-16}-alpine
        environment:
            POSTGRES_DB: ${TEST_POSTGRES_DB:-testDB}
            # You should definitely change the password in production
            POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD:-!TestChangeMe!}
            POSTGRES_USER: ${TEST_POSTGRES_USER:-testApp}
        healthcheck:
            test:
                [
                    'CMD',
                    'pg_isready',
                    '-d',
                    '${POSTGRES_DB:-testDB}',
                    '-U',
                    '${POSTGRES_USER:-testApp}',
                ]
            timeout: 5s
            retries: 5
            start_period: 60s
        volumes:
            - test_database_data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
    ###> doctrine/doctrine-bundle ###
    database_data:
    test_database_data:
###< doctrine/doctrine-bundle ###
