controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# redirect the homepage to the API documentation
homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: '/api'

api_login:
    path: /api/login
